image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
            echo "Server Terminal"
            sleep 5
            cd build
            python -m http.server
    name: http server
  - command: echo "Main Terminal - You are in the top folder of the repository"
    name: main
  - command: |
            echo "Build Terminal"
            source .gitpod_emsdk_set_env.sh
            mkdir build
            cd build
            emcmake cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            make -j 4
            echo "\nIn order to compile the project just type \n"
            echo "make"
            echo ""
    name: build

ports:
  - port: 8000
    # onOpen: open-browser
