image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
            echo "Server Terminal"
            sleep 1
            cd build_emscripten
            python -m http.server
    name: http server
  - command: echo "Main Terminal - You are in the top folder of the repository"
    name: main
  - command: |
            echo "Build Terminal"
            source .gitpod_emsdk_set_env.sh
            mkdir build_emscripten
            cd build_emscripten
            emcmake cmake ..
            make -j 4
            echo "Run make to (re)compile the project"
    name: build

ports:
  - port: 8000
    onOpen: open-browser
